# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My Autistic Self
email: davidakachaos+blog@gmail.com
description:
  nl: >- # this means to ignore newlines until "baseurl:"
    Mijn blog over mezelf als autist en mijn ervaringen met autisme.
    Informatie en uitleg voor mensen zonder autisme, een kijk op de wereld vanuit iemand met autisme.
  en: >- # this means to ignore newlines until "baseurl:"
    My blog about myself as an autist and my experiences with autism.
    Information and explanation for people without autism, a view of the world from someone with autism.
index:
  nl:
  en: /en/
feed:
  nl: /feed.xml
  en: /feed_en.xml

baseurl: '' #"/myautisticself" # the subpath of your site, e.g. /blog
url: "https://myautisticself.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: WesterinkDavid
github_username:  davidakachaos
logo: /assets/img/logo.png
permalink: /:year/:month/:title.html
timezone: Europe/Amsterdam
future: false # Don't publish posts in the future!

tag_page_layout: tagpage
tag_page_dir: tag
tag_disable_tag_pages: true
tag_page_data:
  sitemap: false

ampdir: amp

responsive_image:
  strip: true
  template: _includes/srcset-resized-fallback.html
  output_path_format: assets/resized/%{width}/%{basename}
  sizes:
    - width: 80  # [Required] How wide the resized image will be.
    - width: 20
      quality: 10
    - width: 300
    - width: 250
    - width: 500
    - width: 900
twitter:
  username: WesterinkDavid
  card: summary

facebook:
  publisher: https://www.facebook.com/myautisticself/

social:
  links:
    - https://www.facebook.com/DavidWesterink1984
    - https://www.twitter.com/WesterinkDavid
    - https://www.instagram.com/david.westerink/

author:
  name: David Westerink
  twitter: WesterinkDavid

jekyll_compose:
  auto_open: true
  draft_default_front_matter:
    lang: nl
    tags: autisme
    ref:
    description:
    image:
# Build settings
markdown: kramdown
# default to false, build locally
safe: false
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-email-protect
  - jemoji
  - jekyll-redirect-from

jekyll-minifier:
  compress_javascript: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      lang: "nl"
      ref: ""
      tags: "autisme"

github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
# theme: jekyll-theme-primer
gfm_quirks: paragraph_end
google_site_verification: WHeMLVU_8p80z-fEGUMt0A3fc-NVCLfFxqZX2NktdfE
amp_googleanalytics_id: UA-429677-9
lang: nl

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-429677-9         # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

exclude:
  - deploy.sh
  - tag-generator.py
  - keyword-extractor.py
  - webready-images.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - CNAME
  - package.json
  - yarn.lock
  - node_modules
  - gulpfile.js
  - Gruntfile.js

webmentions:
  username: myautisticself.nl
  debug: false
  js:
    deploy: false
    uglify: false
  paused: false
  legacy_domains: # Some might link to the HTTP version (will be redirected to HTTPS)
    - http://myautisticself.nl
    - http://www.myautisticself.nl
    - https://www.myautisticself.nl
  throttle_lookups:
    last_week: daily
    last_month: weekly
    last_year: every 2 weeks
    older: monthly
  templates:
    bookmarks: _includes/webmentions/bookmarks.html
    count: _includes/webmentions/count.html
    likes: _includes/webmentions/likes.html
    links: _includes/webmentions/links.html
    posts: _includes/webmentions/posts.html
    replies: _includes/webmentions/replies.html
    reposts: _includes/webmentions/reposts.html
    webmentions: _includes/webmentions/webmentions.html
